run:
  concurrency: 4
  timeout: 3m
  go: 1.20
  skip-files:
    - _test\.go
    - _mock\.go

linters:
  disable-all: true
  enable:
    - errcheck
    - gomodguard
    - cyclop
    - gocritic
    - goconst
    - whitespace
    - unused
    - varnamelen
    - funlen
    - goimports
    - lll
    - varnamelen
    - funlen

linters-settings:
  funlen:
    lines: 100

severity:
  default-severity: error
