service: ApiGateway
frameworkVersion: "3"

provider:
  name: aws
  runtime: provided.al2
  architecture: arm64
  region: ${file(config.${opt:stage, self:provider.stage}.json):region}
  environment: ${file(env.${opt:stage, self:provider.stage}.json)}
  iam:
    role:
      statements: ${file(config.${opt:stage, self:provider.stage}.json):iamRoleStatements}

package:
  individually: true

functions:
  login:
    handler: bootstrap
    package:
      artifact: build/login/login.zip
    events:
      - http:
          method: POST
          path: /login
          cors: true

  register:
    handler: bootstrap
    package:
      artifact: build/register/register.zip
    events:
      - http:
          method: POST
          path: /register
          cors: true

  getAccessTokenViaRefreshToken:
    handler: bootstrap
    package:
      artifact: build/getAccessTokenViaRefreshToken/getAccessTokenViaRefreshToken.zip
    events:
      - http:
          method: GET
          path: /user/refreshToken/{refreshToken}
          cors: true

  updateUserById:
    handler: bootstrap
    package:
      artifact: build/updateUserById/updateUserById.zip
    events:
      - http:
          method: PATCH
          path: /user
          cors: true
