// Code generated by MockGen. DO NOT EDIT.
// Source: internal/user/service.go
//
// Generated by this command:
//
//	mockgen --source=internal/user/service.go --destination=internal/user/service_mock.go --package=user
//
// Package user is a generated GoMock package.
package user

import (
	jwt_generator "api-gateway/pkg/jwt_generator"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// VerifyAccessToken mocks base method.
func (m *MockService) VerifyAccessToken(ctx context.Context, accessToken string) (*jwt_generator.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", ctx, accessToken)
	ret0, _ := ret[0].(*jwt_generator.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockServiceMockRecorder) VerifyAccessToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockService)(nil).VerifyAccessToken), ctx, accessToken)
}
