name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

# env:
#  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
#  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    needs:
      - lint

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        shell: bash
        run: |
          make build
          make zip
          rm build/**/bootstrap
          zip -r build.zip build

      - name: Upload build files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
          if-no-files-found: error

  unit-test:
    needs:
      - build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test -tags=unit -coverprofile=coverage.out -covermode=atomic ./...

      - name: Code analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      - name: Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  #  contract-test:
  #    needs:
  #      - unit-test
  #
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #
  #      - uses: actions/setup-go@v4
  #        with:
  #          go-version: "1.21"
  #
  #      - name: Install pact-go CLI
  #        run: |
  #          go install github.com/pact-foundation/pact-go/v2@2.x.x
  #          pact-go -l DEBUG install -d /tmp
  #
  #      - name: Run contract tests
  #        env:
  #          PACT_LOG_LEVEL: DEBUG
  #        run: make contract-test
  #
  #      - name: Publish contracts
  #        uses: pactflow/actions/publish-pact-files@v1.0.1
  #        env:
  #          pactfiles: pacts/*.json
  #          version: ${{ github.sha }}

  security-analysis:
    needs:
      - unit-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security analysis with gosec
        uses: securego/gosec@master
        with:
          args: -exclude-generated ./...

  #  can-i-deploy-to-dev:
  #    needs:
  #      - security-analysis
  #
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #
  #      - run: docker pull pactfoundation/pact-cli:latest
  #
  #      - name: Can I Deploy?
  #        uses: pactflow/actions/can-i-deploy@v1.0.1
  #        env:
  #          application_name: API-Gateway
  #          version: ${{ github.sha }}
  #          to_environment: dev

  deploy-to-dev:
    environment: dev
    needs:
      - security-analysis

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Prepare Build Files
        run: |
          unzip build.zip
          rm -rf build.zip

      - name: Download AWS Config
        run: |
          aws s3 cp ${{ secrets.S3_CONFIG_FILE }} .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Prepare Environment Variables
        run: |
          touch env.dev.json
          echo '{
            "JWT_PRIVATE_KEY": "${{ secrets.JWT_PRIVATE_KEY }}",
            "JWT_PUBLIC_KEY": "${{ secrets.JWT_PUBLIC_KEY }}",
            "USER_API_GET_USER_BY_ID_FUNCTION_NAME": "${{ secrets.USER_API_GET_USER_BY_ID_FUNCTION_NAME }}",
            "USER_API_REGISTER_FUNCTION_NAME": "${{ secrets.USER_API_REGISTER_FUNCTION_NAME }}",
            "USER_API_LOGIN_FUNCTION_NAME": "${{ secrets.USER_API_LOGIN_FUNCTION_NAME }}",
            "USER_API_GET_ACCESS_TOKEN_VIA_REFRESH_TOKEN_FUNCTION_NAME": "${{ secrets.USER_API_GET_ACCESS_TOKEN_VIA_REFRESH_TOKEN_FUNCTION_NAME }}",
            "USER_API_UPDATE_USER_BY_ID_FUNCTION_NAME": "${{ secrets.USER_API_UPDATE_USER_BY_ID_FUNCTION_NAME }}"
          }' > env.dev.json

      - name: Deploy To Development Environment
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  #  record-deployment-for-dev-environment:
  #    needs:
  #      - deploy-to-dev
  #
  #    runs-on: ubuntu-latest
  #    steps:
  #      - run: docker pull pactfoundation/pact-cli:latest
  #
  #      - uses: pactflow/actions/record-deployment@v1.0.1
  #        env:
  #          application_name: API-Gateway
  #          version: ${{ github.sha }}
  #          environment: dev

  #  can-i-deploy-to-prod:
  #    needs:
  #      - record-deployment-for-dev-environment
  #
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #
  #      - run: docker pull pactfoundation/pact-cli:latest
  #
  #      - name: Can I Deploy To Production?
  #        uses: pactflow/actions/can-i-deploy@v1.0.1
  #        env:
  #          application_name: API-Gateway
  #          version: ${{ github.sha }}
  #          to_environment: production

  deploy-to-prod:
    environment: production
    needs:
      - deploy-to-dev

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Prepare Build Files
        run: |
          unzip build.zip
          rm -rf build.zip

      - name: Download AWS Config
        run: |
          aws s3 cp ${{ secrets.S3_CONFIG_FILE }} .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Prepare Environment Variables
        run: |
          touch env.production.json
          echo '{
            "JWT_PRIVATE_KEY": "${{ secrets.JWT_PRIVATE_KEY }}",
            "JWT_PUBLIC_KEY": "${{ secrets.JWT_PUBLIC_KEY }}",
            "USER_API_GET_USER_BY_ID_FUNCTION_NAME": "${{ secrets.USER_API_GET_USER_BY_ID_FUNCTION_NAME }}",
            "USER_API_REGISTER_FUNCTION_NAME": "${{ secrets.USER_API_REGISTER_FUNCTION_NAME }}",
            "USER_API_LOGIN_FUNCTION_NAME": "${{ secrets.USER_API_LOGIN_FUNCTION_NAME }}",
            "USER_API_GET_ACCESS_TOKEN_VIA_REFRESH_TOKEN_FUNCTION_NAME": "${{ secrets.USER_API_GET_ACCESS_TOKEN_VIA_REFRESH_TOKEN_FUNCTION_NAME }}",
            "USER_API_UPDATE_USER_BY_ID_FUNCTION_NAME": "${{ secrets.USER_API_UPDATE_USER_BY_ID_FUNCTION_NAME }}"
          }' > env.production.json

      - name: Deploy To Production Environment
        uses: serverless/github-action@v3.2
        with:
          args: deploy --stage production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#  record-deployment-for-prod-environment:
#    environment: production
#    needs:
#      - deploy-to-prod
#
#    runs-on: ubuntu-latest
#    steps:
#      - run: docker pull pactfoundation/pact-cli:latest
#
#      - uses: pactflow/actions/record-deployment@v1.0.1
#        env:
#          application_name: API-Gateway
#          version: ${{ github.sha }}
#          environment: production
